inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

Lint/BooleanSymbol:
  Enabled: false

Lint/EmptyBlock:
  Exclude:
    - spec/dummy/db/schema.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Lint/MissingSuper:
  Enabled: false

Lint/ScriptPermission:
  Exclude:
    - spec/dummy/bin/*

Naming/BlockForwarding:
  Enabled: false
